### ISSUE TITLE
Mocks with the same verifiable invocation setup multiple times

### ISSUE THREAD

**Issue by roblourens** [florinn/typemoq#10]
```
const m = Mock.ofInstance(a => { });
m.setup(x => x(It.isValue(0))).returns(() => 0).verifiable();
m.setup(x => x(It.isValue(0))).returns(() => 0).verifiable();
m.object(0);
m.object(0);

m.verifyAll();
```
This fails with `Verify Exception: Expected invocation on the mock 2 times, invoked 1 times`. Is this not a supported scenario? I have a test where I set up several invocations, and a couple of them end up with the same expected signature. Is it expected that I only register each one once, then verify that it was called the correct number of times?

**Comment by roblourens** [comment]
And is there any way to specify a different return value on later calls?
```
m.setup(x => x()).returns(() => 0);
m.setup(x => x()).returns(() => 1);
m.setup(x => x()).returns(() => 2);
```
always returns 2.

**Comment by florinn** [comment]
These two are indeed related scenarios. 
Starting with the latter, it always returns 2 because until now only the newest setup was being considered. This also explains why the first verifiable is failing in the former case.

I've just added some support for record/replay scenarios such that:

- if there is a single registered setup then it is always matched
- if there are more registered setups then they are matched in the reversed registration order

So now the invocations in your first scenario should get verified and for the second scenario:

```
mock.setup(x => x()).returns(() => 0);
mock.setup(x => x()).returns(() => 1);
mock.setup(x => x()).returns(() => 2);

expect(mock.object()).to.eq(2);
expect(mock.object()).to.eq(1);
expect(mock.object()).to.eq(0);
expect(() => mock.object()).to.throw(MockException);
```

Let me know what you think.

**Comment by roblourens** [comment]
Cool, thanks! Why in reverse order though, what do you think about replaying in the same order that the record happened?
```
mock.setup(x => x()).returns(() => 0);
mock.setup(x => x()).returns(() => 1);
mock.setup(x => x()).returns(() => 2);

expect(mock.object()).to.eq(0);
expect(mock.object()).to.eq(1);
expect(mock.object()).to.eq(2);
expect(() => mock.object()).to.throw(MockException);
```

**Comment by florinn** [comment]
I guess it does make more sense to replay them in the order they were recorded. I've made the necessary changes.

Typemoq ver 0.1.1 is available and it includes these changes.

Please give it a try and let me know if you have any comments.

**Comment by deneboulton** [comment]
Hi, would you be able to verify if multiple registered setups work with `Mock.ofType<Interface>`  when the matcher is exactly the same, please?
From the docs and the above example I expected that it would.

I have code that looks like this:
```
const mock = TypeMoq.Mock.ofType<MyInterface>();
// setup for first call
mock
    .setup(f => f.funcThatReturnsPromise())
    .returns(() => Promise.resolve(valueA));
// setup for second call
mock
    .setup(f => f.funcThatReturnsPromise())
    .returns(() => Promise.resolve(valueB));
```

What happens is that the second setup trumps the first; so the first call receives `valueB` but the second call receives `undefined`. 
I found it interesting that all subsequent calls after the first return `undefined` and not `valueB` - though naturally both of those outcomes are undesirable as we want `callA -> valueA` & `callB -> valueB`.

If I remove the second setup then all calls to `funcThatReturnsPromise` returns `valueA` as expected.

Previously this test setup code differed in that the setups were both different because `funcThatReturnsPromise` was receiving a value, so:
```
mock
    .setup(f => f.funcThatReturnsPromise(inputA))
    .returns(() => Promise.resolve(valueA));
mock
    .setup(f => f.funcThatReturnsPromise(inputB))
    .returns(() => Promise.resolve(valueB));
```

This worked fine, so a call using `inputA` returned `valueA` and so on.

Any help would be much appreciated, thanks.
