### ISSUE TITLE
How to mock interface when there is no concrete type?

### ISSUE THREAD

**Issue by JoshMcCullough** [florinn/typemoq#3]
Hi, thanks for `typemoq`! Just getting started with it and I'm not sure what to do. Say I want to mock `http.IncomingMessage`, how would I do that? I have to provide a constructor argument, but it's unclear to me how to do so without implementing the interface myself, and using that class as the constructor argument.

    import * as Moq from "typemoq";
    import {IncomingMessage} from "http";    
    
    var mockRequest = Moq.Mock.ofType<IncomingMessage>(???);

**Comment by lowkay** [comment]
Howdy,

That's exactly what you have to do unfortunately. The problem is that interfaces do not emit anything and so there's no way for TypeMoq to (easily) generate a compatible object at runtime.

I suggest you create a dummy implementation for the interface and use that as you constructor argument, this will then emit JavaScript and TypeMoq can enumerate the properties and methods at runtime successfully. The dummy implementation doesn't have to do anything - default constructor, return nulls / do nothing, it's just there to provide something for TypeMoq to mock.

It is a hoop to jump through, but it is no different to other mocking frameworks in JS where you have to provide something concrete to mock.

Potentially this could be solved in the future using type metadata or proxies, but those APIs aren't well-formed enough yet.

**Comment by JoshMcCullough** [comment]
Thanks, makes sense.

**Comment by ffMathy** [comment]
Substitute.js solves this via EcmaScript's proxy object.

https://www.npmjs.com/package/@fluffy-spoon/substitute
