### ISSUE TITLE
Doesn't support TypeScript 1.6 npm package typing resolving

### ISSUE THREAD

**Issue by aleung** [florinn/typemoq#4]
TypeScript 1.6 has introduced a new way to load typings that are bundled with npm packages:
https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

I tried to add a line into typemoq `packages.json` to declare the typing file:

      "typings": "dist/typemoq.node.d.ts",

But I got error when compile my project which imports typemoq:

    error TS2656: Exported external package typings file 'C:/test/node_modules/typemoq/dist/typemoq.node.d.ts' is not a module. Please contact the package author to update the package definition.

**Comment by ndarilek** [comment]
Just came to report this as well. Did you ever find a solution? Fairly new to TS so I don't really know what the best path forward is.

Thanks.

**Comment by pgatilov** [comment]
Here's how we've solved this.
We use npm typings module as a dev dependency. Inside typings.json, we have the following:
`{
  "name": "hidden",
  "version": false,
  "dependencies": {},
  "ambientDependencies": {
    "es6-shim": "github:DefinitelyTyped/DefinitelyTyped/es6-shim/es6-shim.d.ts#4de74cb527395c13ba20b438c3a7a419ad931f1c",
    "jasmine": "registry:dt/jasmine#2.2.0+20160412134438",
    "systemjs": "registry:dt/systemjs#0.18.4+20160316155526",
    "typemoq": "file:.\\node_modules\\typemoq\\typemoq.d.ts"
  }
}`

That line with typemoq tells to take definitions from the npm package. With the help of
`"postinstall": "typings install"`
inside package.json, everything gets into place when we run 'npm install'

Check out documentation on https://github.com/typings/typings for more info on the typings module.

**Comment by florinn** [comment]
Latest TypeMoq (version 0.1.0) should support the TypeScript 1.6 npm package typing resolving.
Please verify and report back the status of this issue.

**Comment by erdeszt** [comment]
The fix of the issue #8 suggests that this problem still exists(i.e. you need to explicitly reference the `typemoq.node.d.ts` file). It might be related to the fact that the import syntax has changed in the newer versions of typescript to: `import * as typemoq from "typemoq"` and you have to provide the definition files in a different format(hence the `TS2656` error).

**Comment by roblourens** [comment]
@pgatilov This doesn't work for me - TS complains that there are duplicate definitions because it's able to find the .d.ts in node_modules, and the one in typings. I just can't get this to work at all. I can `require('typemoq')` out of the box, but I don't have intellisense unless I can use the import syntax. This is all really confusing.

**Comment by pgatilov** [comment]
@roblourens The trick is - we don't import it at all. It is simply available as an ambient type, like this:

```
const mock = TypeMoq.Mock.ofType<T>(T);
```

or you can create a handy alias:
```
import Mock = TypeMoq.Mock;

const mock = Mock.ofType<T>(T);
```

and don't forget to load the typemoq.js via direct script reference in your HTML file.

**Comment by roblourens** [comment]
Oh, you're doing this for the browser, and I'm trying to use it in Node. I can make it available as an ambient type, but at runtime I need to have something actually calling require.

**Comment by pgatilov** [comment]
I have no experience working with Node unfortunately, but I believe there should be a way to require the js file (not d.ts) so that Typescript compiler ignores it. Perhaps you can find it.

**Comment by roblourens** [comment]
Here's what I think I know -
`typemoq.node.d.ts` needs to be an external module, i.e. no triple-slash reference and it needs to export things at the top level. That's required for using 'typings' in the package.json. But you also need ambient typings for the browser case. How can you have both? I don't know. If you have a node.d.ts file that re-exports the ambient typings, you need to explicitly add the original .d.ts to your build, because your module can't have a triple-slash reference.

If I install both .d.ts to my typings folder, that would work except that I get errors for duplicate definitions, because TS finds it in both places.

So here's what I'm doing - install just the ambient typings to my typings folder like above, then 

`const TypeMoq: ITypeMoqStatic = require('typemoq');`

Then I have both intellisense, and the runtime require. The typings come from the file in typings/ which is part of the build.

No clue what the right way to do this is - bundling typings that work as a module *and* as ambient typings.

**Comment by roblourens** [comment]
What I said above actually doesn't work totally right, but I think i have a better solution. If I replace `typemode.node.d.ts` with the contents of `typemoq.d.ts` plus the line `export = TypeMoq`, then everything works perfectly. It should be easy to do that in the build, but I'm not sure how to make gulp do that.

**Comment by florinn** [comment]
@roblourens Following your lead I came to a point where `typemoq.node.d.ts` has the content of `typemoq.d.ts` plus `export {TypeMoq, typemoq}`, then I'm able to use `import {TypeMoq, typemoq} from 'typemoq'`. 
If I try to export only `TypeMoq` then at runtime I get `TypeError: Cannot read property 'Mock' of undefined`. 

I've added an example in [this gist](https://gist.github.com/florinn/2cf74fb576b2fc80390e0cf09c6fb898).

Please let me know if all this makes sense.

**Comment by roblourens** [comment]
You should actually be using `import {Mock} from 'typemoq'` or `import * as TypeMoq from 'typemoq'`. In the Node case, you aren't using that typemoq global. I think that's only relevant for the browser. The fact that you have a module wrapping everything together makes it unnecessary. And the reason that fails at runtime is that you're adding an extra level of modules in TS that doesn't exist at runtime. When you export two things, you're saying there's a module with those two things. But actually TypeMoq *is* the module you want to export, hence `export = TypeMoq`.

Does that make sense? I've learned a few things trying to figure this stuff out.

**Comment by florinn** [comment]
Indeed, after a few changes like in [this other gist](https://gist.github.com/florinn/5927acb97434b64e7df1963873194446), I'm able to use `import { TypeMoqStatic as TypeMoq } from 'typemoq'` (for some reason `export = TypeMoq` or `export default TypeMoq` fail at runtime in my test env, only `export { TypeMoqStatic }` seems to work fine... btw for these tests I'm using TypeScript 1.8.29.0).

Afaik this import construct works only for nodejs, so the `typemoq` global would be still needed for browsers. This means we could end up with 2 different ways of using typemoq:
* nodejs:
import { TypeMoqStatic as TypeMoq } from 'typemoq'
var mock: TypeMoq.Mock<IFoo> = **TypeMoq**.Mock.ofType(Foo);

* browsers:
`/// <reference path="./node_modules/typemoq/typemoq.d.ts" />`
var mock: TypeMoq.Mock<IFoo> = **typemoq**.Mock.ofType(Foo);

To me it would appear a bit confusing when using typemoq. What do you think?

**Comment by roblourens** [comment]
Why do those others fail at runtime? To be clear, I have

typemoq.node.d.ts:
```
<.d.ts content...>
export = TypeMoq;
```
and

app.ts:
```
import {Mock} from 'typemoq'
Mock.ofType(...
```


 And seems like since you're doing 
```
    if (typeof module !== "undefined" && module.exports) {
        exports = module.exports = TypeMoqStatic;
    }
    exports.TypeMoqStatic = TypeMoqStatic;
```

and exporting TypeMoqStatic as the top-level thing, and effectively setting TypeMoqStatic.TypeMoqStatic = TypeMoqStatic then either should work.

Yeah, there are two ways of doing things- with and without modules. And you can use the module version in the browser if you're using AMD modules. That's just the state of TS/JS right now. And that's true right now as well, it's just that the module way doesn't work out of the box, and that's what I'm trying to fix.

**Comment by florinn** [comment]
@roblourens  Many thanks for taking the time to explain to me these intricacies.

Latest typemoq (ver 0.2.0) should now support the TS 1.6+ import form:
```typescript
import * as TypeMoq from "typemoq";
```

Please give it a try and let me know how it goes.

**Comment by roblourens** [comment]
This works perfectly, thanks! I think that in the future, using modules will be more standardized as a best practice - for now, stuff's confusing.

In case anyone else hits this, I ran into Microsoft/TypeScript#8053 after upgrading to 0.2.0. Got the error message from TS, `Cannot read property 'parent' of undefined`. Looks like it will be fixed in the next update, for now I downgraded to TS 1.8.7.
