### ISSUE TITLE
Problem with global mocking - karma - phantomjs - jspm

### ISSUE THREAD

**Issue by b091** [florinn/typemoq#9]
Hi,

first of all thanks for this great promising project!

I wanted to use it but I found some problem maybe you can help me.
When  I run my test with globalmock i get

>   PhantomJS 2.1.1 (Mac OS X 0.0.0)
      Property description must be an object.
      defineProperty@[native code]
      forEach
      with

there is only one test with only one it with code copied from your tests.
Error occurs at [this line](https://github.com/florinn/typemoq/blob/master/dist/typemoq.js#L1220) 

[here is my example](https://github.com/b091/scorm-api-wrapper-ts/tree/typemoqissue)
You can just clone it and then:
`npm install`
`npm test`

**Comment by florinn** [comment]
TypeMoq global mocking makes use of `Object.defineProperty` which unfortunately appears not to be supported by PhantomJS/WebKit (the request crashes with 'Attempting to change access mechanism for an unconfigurable property').

It looks the issue is fairly well known:
http://stackoverflow.com/questions/30629337/jasmine-phantomjs-ignoring-definegetter-method
https://bugs.webkit.org/show_bug.cgi?id=36423
